use phf::phf_map;

use super::{connection, keys, string};
use super::{Args, Error, Execute, Quit, Unimplemented};

pub enum Command {
    Unimplemented(Unimplemented),
    Quit(Quit),
    Get(string::Get),
    Set(string::Set),
    Append(string::Append),
    Strlen(string::Strlen),
    Del(keys::Del),
    Setbit(string::Setbit),
    Getbit(string::Getbit),
    Bitfield(string::Bitfield),
    GetRange(string::GetRange),
    SetRange(string::SetRange),
    Incr(string::Incr),
    Keys(keys::Keys),
    Ping(connection::Ping),
    Echo(connection::Echo),
}

impl Command {
    pub fn to_execute(&self) -> &(dyn Execute + Send + Sync) {
        match self {
            Command::Unimplemented(s) => s,
            Command::Quit(s) => s,
            Command::Get(s) => s,
            Command::Set(s) => s,
            Command::Append(s) => s,
            Command::Strlen(s) => s,
            Command::Del(s) => s,
            Command::Setbit(s) => s,
            Command::Getbit(s) => s,
            Command::Bitfield(s) => s,
            Command::GetRange(s) => s,
            Command::SetRange(s) => s,
            Command::Incr(s) => s,
            Command::Keys(s) => s,
            Command::Ping(s) => s,
            Command::Echo(s) => s,
        }
    }
}

type NewCmd = fn(Args) -> Result<Command, Error>;

pub static COMMANDS: phf::Map<&'static [u8], NewCmd> = phf_map! {
    // b"MODULE" => Unimplemented::new,
    b"GET" => string::Get::new,
    b"SET" => string::Set::new,
    b"SETNX" => string::Set::new,
    b"SETEX" => string::Set::new,
    b"PSETEX" => string::Set::new,
    b"APPEND" => string::Append::new,
    b"STRLEN" => string::Strlen::new,
    b"DEL" => keys::Del::new,
    b"UNLINK" => keys::Del::new,
    b"EXISTS" => Unimplemented::new,
    b"SETBIT" => string::Setbit::new,
    b"GETBIT" => string::Getbit::new,
    b"BITFIELD" => string::Bitfield::new,
    b"SETRANGE" => string::SetRange::new,
    b"GETRANGE" => string::GetRange::new,
    b"SUBSTR" => string::GetRange::new,
    b"INCR" => string::Incr::new,
    b"DECR" => string::Incr::new,
    b"MGET" => Unimplemented::new,
    b"RPUSH" => Unimplemented::new,
    b"LPUSH" => Unimplemented::new,
    b"RPUSHX" => Unimplemented::new,
    b"LPUSHX" => Unimplemented::new,
    b"LINSERT9" => Unimplemented::new,
    b"RPOP" => Unimplemented::new,
    b"LPOP" => Unimplemented::new,
    b"BRPOP" => Unimplemented::new,
    b"BRPOPLPUSH" => Unimplemented::new,
    b"BLPOP" => Unimplemented::new,
    b"LLEN" => Unimplemented::new,
    b"LINDEX" => Unimplemented::new,
    b"LSET" => Unimplemented::new,
    b"LRANGE" => Unimplemented::new,
    b"LTRIM" => Unimplemented::new,
    b"LREM" => Unimplemented::new,
    b"RPOPLPUSH" => Unimplemented::new,
    b"SADD" => Unimplemented::new,
    b"SREM" => Unimplemented::new,
    b"SMOVE" => Unimplemented::new,
    b"SISMEMBER" => Unimplemented::new,
    b"SCARD" => Unimplemented::new,
    b"SPOP" => Unimplemented::new,
    b"SRANDMEMBER" => Unimplemented::new,
    b"SINTER" => Unimplemented::new,
    b"SINTERSTORE" => Unimplemented::new,
    b"SUNION" => Unimplemented::new,
    b"SUNIONSTORE" => Unimplemented::new,
    b"SDIFF" => Unimplemented::new,
    b"SDIFFSTORE" => Unimplemented::new,
    b"SMEMBERS" => Unimplemented::new,
    b"SSCAN" => Unimplemented::new,
    b"ZADD" => Unimplemented::new,
    b"ZINCRBY" => Unimplemented::new,
    b"ZREM" => Unimplemented::new,
    b"ZREMRANGEBYSCORE" => Unimplemented::new,
    b"ZREMRANGEBYRANK" => Unimplemented::new,
    b"ZREMRANGEBYLEX" => Unimplemented::new,
    b"ZUNIONSTORE" => Unimplemented::new,
    b"ZINTERSTORE" => Unimplemented::new,
    b"ZRANGE" => Unimplemented::new,
    b"ZRANGEBYSCORE" => Unimplemented::new,
    b"ZREVRANGEBYSCORE" => Unimplemented::new,
    b"ZRANGEBYLEX" => Unimplemented::new,
    b"ZREVRANGEBYLEX" => Unimplemented::new,
    b"ZCOUNT" => Unimplemented::new,
    b"ZLEXCOUNT" => Unimplemented::new,
    b"ZREVRANGE" => Unimplemented::new,
    b"ZCARD" => Unimplemented::new,
    b"ZSCORE" => Unimplemented::new,
    b"ZRANK" => Unimplemented::new,
    b"ZREVRANK" => Unimplemented::new,
    b"ZSCAN" => Unimplemented::new,
    b"ZPOPMIN" => Unimplemented::new,
    b"ZPOPMAX" => Unimplemented::new,
    b"BZPOPMIN" => Unimplemented::new,
    b"BZPOPMAX" => Unimplemented::new,
    b"HSET" => Unimplemented::new,
    b"HSETNX" => Unimplemented::new,
    b"HGET" => Unimplemented::new,
    b"HMSET" => Unimplemented::new,
    b"HMGET" => Unimplemented::new,
    b"HINCRBY" => Unimplemented::new,
    b"HINCRBYFLOAT" => Unimplemented::new,
    b"HDEL" => Unimplemented::new,
    b"HLEN" => Unimplemented::new,
    b"HSTRLEN" => Unimplemented::new,
    b"HKEYS" => Unimplemented::new,
    b"HVALS" => Unimplemented::new,
    b"HGETALL" => Unimplemented::new,
    b"HEXISTS" => Unimplemented::new,
    b"HSCAN" => Unimplemented::new,
    b"INCRBY" => string::Incr::new,
    b"DECRBY" => string::Incr::new,
    b"INCRBYFLOAT" => Unimplemented::new,
    b"GETSET" => Unimplemented::new,
    b"MSET" => Unimplemented::new,
    b"MSETNX" => Unimplemented::new,
    b"RANDOMKEY" => Unimplemented::new,
    b"SELECT" => Unimplemented::new,
    b"SWAPDB" => Unimplemented::new,
    b"MOVE" => Unimplemented::new,
    b"RENAME" => Unimplemented::new,
    b"RENAMENX" => Unimplemented::new,
    b"EXPIRE" => Unimplemented::new,
    b"EXPIREAT" => Unimplemented::new,
    b"PEXPIRE" => Unimplemented::new,
    b"PEXPIREAT" => Unimplemented::new,
    b"KEYS" => keys::Keys::new,
    b"SCAN" => Unimplemented::new,
    b"DBSIZE" => Unimplemented::new,
    b"AUTH" => Unimplemented::new,
    b"PING" => connection::Ping::new,
    b"ECHO" => connection::Echo::new,
    b"SAVE" => Unimplemented::new,
    b"BGSAVE" => Unimplemented::new,
    b"BGREWRITEAOF" => Unimplemented::new,
    b"SHUTDOWN" => Unimplemented::new,
    b"LASTSAVE" => Unimplemented::new,
    b"TYPE" => Unimplemented::new,
    b"MULTI" => Unimplemented::new,
    b"EXEC" => Unimplemented::new,
    b"DISCARD" => Unimplemented::new,
    b"SYNC" => Unimplemented::new,
    b"PSYNC" => Unimplemented::new,
    b"REPLCONF" => Unimplemented::new,
    b"FLUSHDB" => Unimplemented::new,
    b"FLUSHALL" => Unimplemented::new,
    b"SORT" => Unimplemented::new,
    b"INFO" => Unimplemented::new,
    b"MONITOR" => Unimplemented::new,
    b"TTL" => Unimplemented::new,
    b"TOUCH" => Unimplemented::new,
    b"PTTL" => Unimplemented::new,
    b"PERSIST" => Unimplemented::new,
    b"SLAVEOF" => Unimplemented::new,
    b"REPLICAOF" => Unimplemented::new,
    b"ROLE" => Unimplemented::new,
    b"DEBUG" => Unimplemented::new,
    b"CONFIG" => Unimplemented::new,
    b"SUBSCRIBE" => Unimplemented::new,
    b"UNSUBSCRIBE" => Unimplemented::new,
    b"PSUBSCRIBE" => Unimplemented::new,
    b"PUNSUBSCRIBE" => Unimplemented::new,
    b"PUBLISH" => Unimplemented::new,
    b"PUBSUB" => Unimplemented::new,
    b"WATCH" => Unimplemented::new,
    b"UNWATCH" => Unimplemented::new,
    b"CLUSTER" => Unimplemented::new,
    b"RESTORE" => Unimplemented::new,
    b"RESTORE-ASKING" => Unimplemented::new,
    b"MIGRATE" => Unimplemented::new,
    b"ASKING" => Unimplemented::new,
    b"READONLY" => Unimplemented::new,
    b"READWRITE" => Unimplemented::new,
    b"DUMP" => Unimplemented::new,
    b"OBJECT" => Unimplemented::new,
    b"MEMORY" => Unimplemented::new,
    b"CLIENT" => Unimplemented::new,
    b"EVAL" => Unimplemented::new,
    b"EVALSHA" => Unimplemented::new,
    b"SLOWLOG" => Unimplemented::new,
    b"SCRIPT" => Unimplemented::new,
    b"TIME" => Unimplemented::new,
    b"BITOP" => Unimplemented::new,
    b"BITCOUNT" => Unimplemented::new,
    b"BITPOS" => Unimplemented::new,
    b"WAIT" => Unimplemented::new,
    b"COMMAND" => Unimplemented::new,
    b"GEOADD" => Unimplemented::new,
    b"GEORADIUS" => Unimplemented::new,
    b"GEORADIUS_RO" => Unimplemented::new,
    b"GEORADIUSBYMEMBER" => Unimplemented::new,
    b"GEORADIUSBYMEMBER_RO" => Unimplemented::new,
    b"GEOHASH" => Unimplemented::new,
    b"GEOPOS" => Unimplemented::new,
    b"GEODIST" => Unimplemented::new,
    b"PFSELFTEST" => Unimplemented::new,
    b"PFADD" => Unimplemented::new,
    b"PFCOUNT" => Unimplemented::new,
    b"PFMERGE" => Unimplemented::new,
    b"PFDEBUG" => Unimplemented::new,
    b"XADD" => Unimplemented::new,
    b"XRANGE" => Unimplemented::new,
    b"XREVRANGE" => Unimplemented::new,
    b"XLEN" => Unimplemented::new,
    b"XREAD" => Unimplemented::new,
    b"XREADGROUP" => Unimplemented::new,
    b"XGROUP" => Unimplemented::new,
    b"XACK" => Unimplemented::new,
    b"XPENDING" => Unimplemented::new,
    b"XCLAIM" => Unimplemented::new,
    b"XINFO" => Unimplemented::new,
    b"XDEL" => Unimplemented::new,
    b"XTRIM" => Unimplemented::new,
    b"POST" => Unimplemented::new,
    b"HOST:" => Unimplemented::new,
    b"LATENCY" => Unimplemented::new,
    b"QUIT" => Quit::new,
};
